test/t/mocks/pacman: Print error if no packages own file

diff --git a/test/t/mocks/pacman b/test/t/mocks/pacman
--- a/test/t/mocks/pacman
+++ b/test/t/mocks/pacman
@@ -165,6 +165,7 @@ function pacman() {
 
 					if ! $found
 					then
+						printf 'Error: no package owns %q\n' "${args[0]}" 1>&2
 						exit_code=1
 					fi
 					;;
