aconf-apply: Add confirmations

diff --git a/aconf-apply b/aconf-apply
--- a/aconf-apply
+++ b/aconf-apply
@@ -2,6 +2,37 @@
 set -euo pipefail
 source src/common.sh
 
+Confirm() {
+	local detail_func="$1"
+
+	while true
+	do
+		Log "Proceed? [Y/n/d] "
+		read -r -n 1 answer
+		echo
+		case "$answer" in
+			Y|y|'')
+				return
+				;;
+			N|n)
+				Log "%s\n" "$(Color R "User abort")"
+				exit 1
+				;;
+			D|d)
+				$detail_func
+				continue
+				;;
+			*)
+				continue
+				;;
+		esac
+	done
+}
+
+ParanoidConfirm() {
+	: # TODO: call Confirm when --paranoid is present
+}
+
 AconfCompile
 
 LogEnter "Applying configuration...\n"
@@ -36,7 +67,12 @@ unknown_packages=($(comm -13																			\
 if [[ ${#unknown_packages[@]} != 0 ]]
 then
 	LogEnter "Unpinning %s unknown packages.\n" "$(Color G ${#unknown_packages[@]})"
+
+	function Details() { Log "Unpinning (setting install reason to 'as dependency') the following packages:%s\n" "$(Color M " %s" "${unknown_packages[@]}")" ; }
+	Confirm Details
+
 	Print0Array unknown_packages | sudo xargs -0 pacman --database --asdeps
+
 	LogLeave
 fi
 
@@ -47,22 +83,30 @@ missing_packages=($(comm -23																			\
 
 # Missing installed/unpinned packages (native and foreign packages that are implicitly installed,
 # and listed in the configuration, but not marked as explicitly installed)
-missing_unpinned_packages=($(comm -12 <(PrintArray missing_packages) <(pacman --query --quiet)))
+missing_unpinned_packages=($(comm -12 <(PrintArray missing_packages) <(pacman --query --quiet | sort)))
 
 if [[ ${#missing_unpinned_packages[@]} != 0 ]]
 then
 	LogEnter "Pinning %s unknown packages.\n" "$(Color G ${#missing_unpinned_packages[@]})"
+
+	function Details() { Log "Pinning (setting install reason to 'explicitly installed') the following packages:%s\n" "$(Color M " %s" "${missing_unpinned_packages[@]}")" ; }
+	Confirm Details
+
 	Print0Array missing_unpinned_packages | sudo xargs -0 pacman --database --asexplicit
+
 	LogLeave
 fi
 
 
 # Missing native packages (native packages that are listed in the configuration, but not installed)
-missing_native_packages=($(comm -23 <(PrintArray packages) <(pacman --query --quiet)))
+missing_native_packages=($(comm -23 <(PrintArray packages) <(pacman --query --quiet | sort)))
 
 if [[ ${#missing_native_packages[@]} != 0 ]]
 then
 	LogEnter "Installing %s missing native packages.\n" "$(Color G ${#missing_native_packages[@]})"
+
+	function Details() { Log "Installing the following native packages:%s\n" "$(Color M " %s" "${missing_native_packages[@]}")" ; }
+	ParanoidConfirm Details
 
 	sudo pacman --sync "${missing_native_packages[@]}"
 
@@ -70,11 +114,14 @@ then
 fi
 
 # Missing foreign packages (foreign packages that are listed in the configuration, but not installed)
-missing_foreign_packages=($(comm -23 <(PrintArray foreign_packages) <(pacman --query --quiet)))
+missing_foreign_packages=($(comm -23 <(PrintArray foreign_packages) <(pacman --query --quiet | sort)))
 
 if [[ ${#missing_foreign_packages[@]} != 0 ]]
 then
 	LogEnter "Installing %s missing foreign packages.\n" "$(Color G ${#missing_foreign_packages[@]})"
+
+	function Details() { Log "Installing the following foreign packages:%s\n" "$(Color M " %s" "${missing_foreign_packages[@]}")" ; }
+	ParanoidConfirm Details
 
 	# TODO: use makepkg?
 	pacaur --sync "${missing_foreign_packages[@]}"
@@ -101,6 +148,10 @@ then
 		if [[ ${#orphan_packages[@]} != 0 ]]
 		then
 			LogEnter "Pruning %s orphan packages.\n" "$(Color G ${#orphan_packages[@]})"
+
+			function Details() { Log "Removing the following orphan packages:%s\n" "$(Color M " %s" "${orphan_packages[@]}")" ; }
+			ParanoidConfirm Details
+
 			sudo pacman --remove "${orphan_packages[@]}"
 			LogLeave
 		fi
